const SUPABASE_URL="https://ndlizdfcmmywpwrecskx.supabase.co";
const SUPABASE_KEY="sb_publishable_ggDoRBP2Ul658l-7rHKBPQ_WRrrOZqn";
const supabase=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const app=document.getElementById("app"),authScreen=document.getElementById("auth-screen"),authForm=document.getElementById("auth-form"),authToggle=document.getElementById("auth-toggle"),authTitle=document.getElementById("auth-title"),authSubtitle=document.getElementById("auth-subtitle"),authSubmit=document.getElementById("auth-submit"),nameField=document.getElementById("name-field"),authMessage=document.getElementById("auth-message"),toast=document.getElementById("toast");
let signUpMode=false,currentUser=null,profile=null,goals=null,hydrationTotal=0,currentPage="home";
const workoutTemplate=[["Bodyweight Squats","3 sets × 10 reps"],["Incline Push-ups","3 sets × 8 reps"],["Glute Bridges","3 sets × 12 reps"],["Plank","3 × 20 seconds"]];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const liters=ml=>(ml/1000).toFixed(1)+"L";
const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d.toISOString()};
function toastMsg(m){toast.textContent=m;toast.classList.add("show");clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove("show"),2400)}
function authMsg(m,err=false){authMessage.textContent=m;authMessage.className="message "+(err?"error":"")}
function showAuth(){authScreen.classList.remove("hidden");app.classList.add("hidden")}
function showApp(){authScreen.classList.add("hidden");app.classList.remove("hidden");render("home")}
function requireSupabase(){if(!supabase){authMsg("The Supabase library did not load. Refresh the page or redeploy Mikefit.",true);return false}return true}
async function loadData(){const [p,g,h]=await Promise.all([supabase.from("profiles").select("*").eq("id",currentUser.id).maybeSingle(),supabase.from("user_goals").select("*").eq("user_id",currentUser.id).maybeSingle(),supabase.from("hydration_logs").select("amount_ml").eq("user_id",currentUser.id).gte("logged_at",today())]);if(p.error)throw p.error;if(g.error)throw g.error;if(h.error)throw h.error;profile=p.data||{id:currentUser.id,display_name:currentUser.email?.split("@")[0]||"Mike"};goals=g.data||{daily_water_ml:2500};hydrationTotal=(h.data||[]).reduce((s,r)=>s+Number(r.amount_ml||0),0)}
async function addWater(ml){if(!requireSupabase())return;const {error}=await supabase.from("hydration_logs").insert({user_id:currentUser.id,amount_ml:ml,logged_at:new Date().toISOString()});if(error)throw error;hydrationTotal+=ml;toastMsg("Water logged 💧");render("hydration")}
async function workout(){if(!requireSupabase())return;const {error}=await supabase.from("workout_logs").insert({user_id:currentUser.id,completed_at:new Date().toISOString(),duration_minutes:35,calories_burned:320});if(error)throw error;toastMsg("Workout logged ✓");render("home")}
async function meal(){if(!requireSupabase())return;const name=document.getElementById("meal-name").value.trim();if(!name)return toastMsg("Enter a meal name");const {error}=await supabase.from("meal_logs").insert({user_id:currentUser.id,name,calories:Number(document.getElementById("meal-calories").value||0),protein_g:Number(document.getElementById("meal-protein").value||0),meal_type:"meal",logged_at:new Date().toISOString()});if(error)throw error;toastMsg("Meal logged 🥗");render("nutrition")}
async function saveProfile(){if(!requireSupabase())return;const {error}=await supabase.from("profiles").update({display_name:document.getElementById("profile-name").value.trim()||profile.display_name,height_cm:Number(document.getElementById("profile-height").value)||null,weight_kg:Number(document.getElementById("profile-weight").value)||null}).eq("id",currentUser.id);if(error)throw error;await loadData();toastMsg("Profile saved ✓");render("profile")}
const pages={
home:()=>{const n=esc(profile?.display_name||"Mike"),t=goals?.daily_water_ml||2500,p=Math.min(100,Math.round(hydrationTotal/t*100));return `<header><div><small>MIKEFIT</small><h1>Good afternoon, ${n} 👋</h1></div><div class="avatar">${n[0]?.toUpperCase()||"M"}</div></header><main><section class="hero"><span>TODAY</span><h2>Keep the streak alive.</h2><p>Small actions today build the body you want tomorrow.</p><div class="streak"><strong>7</strong><p>day streak 🔥</p></div></section><section><div class="section-title"><h2>Today's plan</h2><span>2 of 3</span></div><div class="task"><div class="check done">✓</div><div><strong>Morning mobility</strong><small>10 min • Recovery</small></div></div><button class="task task-button" id="home-workout"><div class="check">+</div><div><strong>Full body strength</strong><small>35 min • Beginner</small></div></button><button class="task task-button" id="home-water"><div class="check">+</div><div><strong>Hit your water goal</strong><small>${liters(hydrationTotal)} of ${liters(t)} • ${p}%</small></div></button></section><section class="stats"><div>🔥<strong>7</strong><small>day streak</small></div><div>💧<strong>${liters(hydrationTotal)}</strong><small>of ${liters(t)}</small></div><div>⚡<strong>320</strong><small>calories planned</small></div></section><section><h2>Quick start</h2><div class="quick-grid"><button data-page="workouts">🏋️<strong>Start workout</strong><small>Build strength</small></button><button data-page="nutrition">🥗<strong>Log a meal</strong><small>Track nutrition</small></button><button data-page="hydration">💧<strong>Add water</strong><small>Stay hydrated</small></button><button data-page="progress">📈<strong>View progress</strong><small>See your journey</small></button></div></section></main>`},
workouts:()=>`<header><div><small>WORKOUTS</small><h1>Let's get moving 💪</h1></div><div class="avatar">M</div></header><main><section class="hero"><span>BEGINNER</span><h2>Full Body Strength</h2><p>A simple 35-minute workout designed to build strength without overwhelming you.</p></section><section><h2>Today's workout</h2>${workoutTemplate.map((x,i)=>`<div class="task"><div class="check">${i+1}</div><div><strong>${x[0]}</strong><small>${x[1]}</small></div></div>`).join("")}<button class="primary-button" id="start-workout">Start workout</button></section></main>`,
nutrition:()=>`<header><div><small>NUTRITION</small><h1>Fuel your body 🥗</h1></div><div class="avatar">M</div></header><main><section class="hero"><span>TODAY</span><h2>Balanced meals.</h2><p>Track what you eat and build consistency around your nutrition.</p></section><section><h2>Log a meal</h2><div class="form-card"><label>Meal name<input id="meal-name" placeholder="e.g. Chicken and rice"></label><label>Calories<input id="meal-calories" type="number" min="0" placeholder="500"></label><label>Protein (g)<input id="meal-protein" type="number" min="0" placeholder="30"></label><button class="primary-button" id="save-meal">Save meal</button></div></section></main>`,
hydration:()=>{const t=goals?.daily_water_ml||2500,p=Math.min(100,Math.round(hydrationTotal/t*100));return `<header><div><small>HYDRATION</small><h1>Stay hydrated 💧</h1></div><div class="avatar">M</div></header><main><section class="hero"><span>TODAY</span><h2>${liters(hydrationTotal)} / ${liters(t)}</h2><p>${p}% of your daily target. Keep sipping throughout the day.</p><div class="progress"><i style="width:${p}%"></i></div></section><section><h2>Add water</h2><div class="quick-grid"><button data-water="250">💧<strong>250ml</strong><small>Small glass</small></button><button data-water="500">💧<strong>500ml</strong><small>Bottle</small></button><button data-water="750">💧<strong>750ml</strong><small>Large bottle</small></button><button data-water="1000">💧<strong>1L</strong><small>Big bottle</small></button></div></section></main>`},
progress:()=>`<header><div><small>PROGRESS</small><h1>Your journey 📈</h1></div><div class="avatar">M</div></header><main><section class="hero"><span>THIS WEEK</span><h2>You're showing up.</h2><p>Consistency matters more than perfection. Keep building the habit.</p></section><section class="stats"><div>🔥<strong>7</strong><small>day streak</small></div><div>🏋️<strong>4</strong><small>workouts goal</small></div><div>💧<strong>${liters(hydrationTotal)}</strong><small>today</small></div></section><section><h2>Profile metrics</h2><div class="task"><div class="check">⚖</div><div><strong>${profile?.weight_kg?profile.weight_kg+" kg":"Add weight"}</strong><small>Current weight</small></div></div><div class="task"><div class="check">↕</div><div><strong>${profile?.height_cm?profile.height_cm+" cm":"Add height"}</strong><small>Height</small></div></div></section></main>`,
profile:()=>`<header><div><small>PROFILE</small><h1>Hey ${esc(profile?.display_name||"Mike")} 👋</h1></div><div class="avatar">M</div></header><main><section class="hero"><span>MEMBER</span><h2>Your Mikefit profile</h2><p>Keep your basic details up to date so the app can personalize your plan.</p></section><section><h2>Your details</h2><div class="form-card"><label>Name<input id="profile-name" value="${esc(profile?.display_name||"")}"></label><label>Height (cm)<input id="profile-height" type="number" value="${profile?.height_cm||""}"></label><label>Weight (kg)<input id="profile-weight" type="number" step="0.1" value="${profile?.weight_kg||""}"></label><button class="primary-button" id="save-profile">Save profile</button><button class="secondary-button" id="sign-out">Sign out</button></div></section></main>`};
function nav(){const n=document.createElement("nav");[["home","⌂","Home"],["workouts","◈","Workouts"],["nutrition","◉","Nutrition"],["progress","◒","Progress"],["profile","○","Profile"]].forEach(([p,i,l])=>{const b=document.createElement("button");b.className=p===currentPage?"active":"";b.innerHTML=i+"<small>"+l+"</small>";b.onclick=()=>render(p);n.appendChild(b)});app.appendChild(n)}
function render(p="home"){currentPage=p;app.innerHTML=pages[p]();nav();document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>render(b.dataset.page));document.querySelectorAll("[data-water]").forEach(b=>b.onclick=async()=>{try{await addWater(Number(b.dataset.water))}catch(e){toastMsg(e.message)}});document.getElementById("home-workout")?.addEventListener("click",()=>render("workouts"));document.getElementById("home-water")?.addEventListener("click",()=>render("hydration"));document.getElementById("start-workout")?.addEventListener("click",async()=>{try{await workout()}catch(e){toastMsg(e.message)}});document.getElementById("save-meal")?.addEventListener("click",async()=>{try{await meal()}catch(e){toastMsg(e.message)}});document.getElementById("save-profile")?.addEventListener("click",async()=>{try{await saveProfile()}catch(e){toastMsg(e.message)}});document.getElementById("sign-out")?.addEventListener("click",async()=>{if(supabase)await supabase.auth.signOut();showAuth()})}
authToggle.addEventListener("click",()=>{signUpMode=!signUpMode;authTitle.textContent=signUpMode?"Create your account":"Welcome back 👋";authSubtitle.textContent=signUpMode?"Start your Mikefit journey today.":"Sign in to continue your fitness journey.";nameField.classList.toggle("hidden",!signUpMode);authToggle.textContent=signUpMode?"Already have an account? Sign in":"Need an account? Sign up";authSubmit.textContent=signUpMode?"Create account":"Sign in";authMsg("")});
authForm.addEventListener("submit",async e=>{e.preventDefault();if(!requireSupabase())return;authSubmit.disabled=true;authSubmit.textContent="Please wait…";authMsg("");try{const email=document.getElementById("auth-email").value.trim(),password=document.getElementById("auth-password").value,name=document.getElementById("auth-name").value.trim();if(signUpMode){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{display_name:name||undefined}}});if(error)throw error;if(!data.session)authMsg("Account created. Check your email to confirm, then sign in.");else{currentUser=data.user;await loadData();showApp()}}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;currentUser=data.user;await loadData();showApp()}}catch(e){authMsg(e.message||"Something went wrong.",true)}finally{authSubmit.disabled=false;authSubmit.textContent=signUpMode?"Create account":"Sign in"}});
if(supabase){supabase.auth.onAuthStateChange(async(_event,session)=>{if(!session?.user){currentUser=null;showAuth();return}currentUser=session.user;try{await loadData();showApp()}catch(e){showAuth();authMsg(e.message,true)}});(async()=>{const {data}=await supabase.auth.getSession();if(data.session){currentUser=data.session.user;try{await loadData();showApp()}catch(e){showAuth();authMsg(e.message,true)}}else showAuth()})()}else{showAuth();authMsg("Mikefit loaded, but Supabase did not load. Refresh or redeploy.",true)}