const SUPABASE_URL = "https://ndlizdfcmmywpwrecskx.supabase.co";
const SUPABASE_KEY = "sb_publishable_ggDoRBP2Ul658l-7rHKBPQ_WRrrOZqn";

if (!window.supabase) {
  document.body.innerHTML = '<div class="boot-error"><h2>MikeFit needs one more moment</h2><p>The authentication service did not load.</p><button onclick="location.reload()">Reload</button></div>';
  throw new Error("Supabase library unavailable");
}

const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY, {
  auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true }
});

const $ = id => document.getElementById(id);
const app = $("app");
const authScreen = $("auth-screen");
const authForm = $("auth-form");
const authToggle = $("auth-toggle");
const authSubmitButton = $("auth-submit");
const authTitle = $("auth-title");
const authSubtitle = $("auth-subtitle");
const authName = $("name-field");
const authMessage = $("auth-message");
const toast = $("toast");

let user = null;
let profile = { name: "Mike", goal: "Get stronger & feel energetic", level: "Building consistency", preference: "Home workouts" };
let signupMode = false;
let timerId = null;
let timerPaused = false;
let workoutContext = null;
let booted = false;

const FALLBACK_EXERCISES = {
  "bodyweight squat": { steps: ["Stand with feet about shoulder-width apart.", "Push hips back like sitting into a chair.", "Bend your knees and lower comfortably.", "Drive through your feet to stand tall."], mistakes: "Knees collapsing inward or rushing.", easy: "Use a chair as a target and reduce the depth.", muscles: "Glutes, thighs and core.", image: "/assets/exercises/bodyweight-squat.svg" },
  "incline push-up": { steps: ["Place hands on a sturdy raised surface.", "Keep your body straight from head to heels.", "Bend elbows and lower your chest.", "Push the surface away to return."], mistakes: "Hips sagging or elbows flaring too far out.", easy: "Use a wall or higher counter.", muscles: "Chest, shoulders, arms and core.", image: "/assets/exercises/incline-pushup.svg" },
  "glute bridge": { steps: ["Lie on your back with knees bent and feet flat.", "Keep arms relaxed beside you.", "Squeeze glutes and lift hips.", "Pause, then lower slowly."], mistakes: "Over-arching the lower back.", easy: "Lift your hips only part way if needed.", muscles: "Glutes, hamstrings and core.", image: "/assets/exercises/glute-bridge.svg" },
  "plank": { steps: ["Place forearms under your shoulders.", "Extend legs and brace your stomach.", "Keep your body in one straight line.", "Breathe normally while holding."], mistakes: "Hips sagging, hips too high or holding your breath.", easy: "Put your knees on the floor.", muscles: "Core, shoulders and glutes.", image: "/assets/exercises/plank.svg" },
  "dead bug": { steps: ["Lie on your back with arms up and knees bent.", "Gently brace your stomach.", "Extend one arm and opposite leg slowly.", "Return and switch sides."], mistakes: "Lower back lifting from the floor.", easy: "Move only your arms first.", muscles: "Deep core and hip muscles.", image: "/assets/exercises/dead-bug.svg" },
  "bird dog": { steps: ["Start on hands and knees.", "Reach one arm forward and the opposite leg back.", "Pause with hips level.", "Return and switch sides."], mistakes: "Twisting or lifting the leg too high.", easy: "Lift only one arm or one leg at a time.", muscles: "Core, back, shoulders and glutes.", image: "/assets/exercises/bodyweight-squat.svg" },
  "side plank": { steps: ["Lie on your side with forearm under shoulder.", "Stack or stagger your feet.", "Lift hips into a straight line.", "Hold while breathing normally."], mistakes: "Letting hips drop or shoulders roll forward.", easy: "Keep your bottom knee on the floor.", muscles: "Core, shoulders and hips.", image: "/assets/exercises/side-plank.svg" },
  "reverse lunges": { steps: ["Stand tall with feet comfortable apart.", "Step one foot backward.", "Bend both knees comfortably.", "Push through the front foot to return."], mistakes: "Front knee collapsing inward.", easy: "Hold a wall or chair and take a smaller step.", muscles: "Glutes, thighs and calves.", image: "/assets/exercises/reverse-lunge.svg" },
  "calf raises": { steps: ["Stand tall with feet about hip-width apart.", "Rise slowly onto the balls of your feet.", "Pause at the top.", "Lower heels with control."], mistakes: "Bouncing or rolling the ankles outward.", easy: "Hold a wall or chair.", muscles: "Calves and ankles.", image: "/assets/exercises/calf-raises.svg" },
  "march in place": { steps: ["Stand tall with feet under hips.", "Lift one knee comfortably.", "Lower softly and lift the other.", "Keep a steady rhythm."], mistakes: "Leaning backward or stomping.", easy: "Lift knees lower and slow the pace.", muscles: "Legs, hips and cardiovascular system.", image: "/assets/exercises/march-in-place.svg" },
  "jumping jacks": { steps: ["Start with feet together and arms by sides.", "Jump feet apart while raising arms.", "Land softly with knees slightly bent.", "Return to the start."], mistakes: "Hard landings or locked knees.", easy: "Step one foot out at a time.", muscles: "Legs, shoulders and cardiovascular system.", image: "/assets/exercises/jumping-jacks.svg" },
  "high knees": { steps: ["Stand tall and brace your stomach.", "Drive one knee upward.", "Lower softly and switch legs.", "Pump arms naturally."], mistakes: "Stomping or leaning backward.", easy: "March slowly and lift knees comfortably.", muscles: "Legs, hips and cardiovascular system.", image: "/assets/exercises/high-knees.svg" }
};

const DEFAULT_WORKOUTS = [
  { id: "starter", name: "Full Body Starter", level: "Beginner", category: "Strength", duration_minutes: 20, description: "A simple full-body session for building consistency.", icon: "💪", exercises: ["Bodyweight Squats", "Incline Push-ups", "Glute Bridges", "Plank"] },
  { id: "mobility", name: "Mobility & Core", level: "All levels", category: "Mobility", duration_minutes: 15, description: "Gentle movement for your core, hips and back.", icon: "🧘", exercises: ["Dead Bug", "Bird Dog", "Side Plank", "Glute Bridge"] },
  { id: "cardio", name: "Home Cardio", level: "Beginner", category: "Cardio", duration_minutes: 15, description: "A no-equipment cardio session you can do anywhere.", icon: "🔥", exercises: ["March in Place", "Jumping Jacks", "High Knees", "Bodyweight Squats"] }
];

const esc = value => String(value ?? "").replace(/[&<>\'\"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]));
const localDate = (d = new Date()) => { const x = new Date(d); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`; };
const startOfDay = () => { const d = new Date(); d.setHours(0,0,0,0); return d.toISOString(); };
const endOfDay = () => { const d = new Date(); d.setHours(23,59,59,999); return d.toISOString(); };
const weekStart = () => { const d = new Date(); const day = d.getDay(); const diff = day === 0 ? 6 : day - 1; d.setHours(0,0,0,0); d.setDate(d.getDate() - diff); return d.toISOString(); };
const prefsKey = () => `mikefit_prefs_${user?.id || "guest"}`;
const getPrefs = () => { try { return JSON.parse(localStorage.getItem(prefsKey()) || "{}") || {}; } catch { return {}; } };
const setPrefs = next => localStorage.setItem(prefsKey(), JSON.stringify({ ...getPrefs(), ...next }));
const prefs = () => ({ equipment: "No equipment", duration: 30, ...getPrefs() });

function toastMsg(text, type = "") { if (!toast) return; toast.textContent = text; toast.className = `toast show ${type}`; clearTimeout(toastMsg.t); toastMsg.t = setTimeout(() => toast.className = "toast", 2600); }
function showAuth(message = "") { if (authScreen) authScreen.classList.remove("hidden"); if (app) app.classList.add("hidden"); if (message && authMessage) authMessage.textContent = message; }
async function enterApp(nextUser) { user = nextUser; await loadProfile(); await recordLogin(); showApp(); }
function showApp() { authScreen.classList.add("hidden"); app.classList.remove("hidden"); render("home"); }
async function safe(query, fallback = []) { try { const r = await query(); return r.error ? fallback : (r.data || fallback); } catch { return fallback; } }
async function loadProfile() { if (!user) return; try { const { data } = await db.from("profiles").select("*").eq("id", user.id).maybeSingle(); if (data) profile = { ...profile, ...data }; } catch {} }

async function metrics() {
  if (!user) return { workouts: [], meals: [], water: 0, calories: 0, protein: 0, minutes: 0 };
  const [workouts, meals, water] = await Promise.all([
    safe(() => db.from("workout_logs").select("id,workout_id,duration_minutes,calories_burned,completed_at").eq("user_id", user.id).gte("completed_at", weekStart()).order("completed_at", { ascending: false })),
    safe(() => db.from("meal_logs").select("id,name,calories,protein_g,meal_type,logged_at").eq("user_id", user.id).gte("logged_at", startOfDay()).lte("logged_at", endOfDay()).order("logged_at", { ascending: false })),
    safe(() => db.from("hydration_logs").select("id,amount_ml,logged_at").eq("user_id", user.id).gte("logged_at", startOfDay()).lte("logged_at", endOfDay()).order("logged_at", { ascending: false }))
  ]);
  return { workouts, meals, water: water.reduce((a,r)=>a+Number(r.amount_ml||0),0), calories: meals.reduce((a,r)=>a+Number(r.calories||0),0), protein: meals.reduce((a,r)=>a+Number(r.protein_g||0),0), minutes: workouts.reduce((a,r)=>a+Number(r.duration_minutes||0),0) };
}
async function streak() { if(!user)return 0; const rows=await safe(()=>db.from("login_days").select("login_date").eq("user_id",user.id).order("login_date",{ascending:false}).limit(400),[]); const dates=new Set(rows.map(x=>String(x.login_date).slice(0,10))); if(!dates.size)return 0; let count=0,d=new Date();d.setHours(0,0,0,0);while(dates.has(localDate(d))){count++;d.setDate(d.getDate()-1);}return count; }
async function recordLogin(){if(!user)return;try{await db.from("login_days").upsert({user_id:user.id,login_date:localDate()},{onConflict:"user_id,login_date",ignoreDuplicates:true});}catch{}}
function nav(active){const items=[["home","⌂","Home"],["workouts","◈","Workouts"],["nutrition","◉","Nutrition"],["hydration","💧","Water"],["progress","◒","Progress"],["profile","○","Profile"]];return `<nav>${items.map(([p,icon,label])=>`<button class="nav-item ${active===p?"active":""}" data-page="${p}" aria-label="${label}"><span>${icon}</span><small>${label}</small></button>`).join("")}</nav>`;}
function bindNav(){app.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>render(b.dataset.page));}
function avatar(name){const n=String(name||"M");return `<div class="avatar">${esc(n[0]||"M").toUpperCase()}</div>`;}
function header(kicker,title,subtitle="",name=profile.name){return `<header><div><span class="eyebrow">${esc(kicker)}</span><h1>${title}</h1>${subtitle?`<p class="header-sub">${subtitle}</p>`:""}</div>${avatar(name)}</header>`;}
function pageShell(content,active){app.innerHTML=content+nav(active);bindNav();window.scrollTo({top:0,behavior:"instant"});}

async function home(){const [m,s]=await Promise.all([metrics(),streak()]);const p=prefs();const remaining=Math.max(0,2000-m.water);const workout=await recommendedWorkout();pageShell(`${header("MIKEFIT",`Good ${new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, ${esc(profile.name||"Mike")} 👋`,"Here's the simplest way to move forward today.")}<main><section class="dashboard-hero"><div><span class="eyebrow">TODAY'S FOCUS</span><h2>${esc(workout.name)}</h2><p>${esc(workout.description||"A focused session built around your preferences.")}</p><div class="hero-meta"><span>⏱ ${workout.duration_minutes} min</span><span>🏋️ ${esc(p.equipment)}</span><span>🎯 ${esc(profile.goal)}</span></div><button class="primary-button" data-workout-id="${esc(workout.id)}" id="home-start">Start today's workout</button></div><div class="hero-streak"><strong>${s}</strong><span>day streak 🔥</span></div></section><section class="metric-grid"><button data-page="hydration"><span>💧</span><strong>${(m.water/1000).toFixed(1)}L</strong><small>Water today</small><i><b style="width:${Math.min(100,m.water/2000*100)}%"></b></i></button><button data-page="nutrition"><span>🥗</span><strong>${m.calories}</strong><small>Calories today</small><i><b style="width:${Math.min(100,m.calories/2000*100)}%"></b></i></button><button data-page="progress"><span>🏋️</span><strong>${m.workouts.length}</strong><small>Workouts this week</small><i><b style="width:${Math.min(100,m.workouts.length/4*100)}%"></b></i></button><button data-page="progress"><span>⏱️</span><strong>${m.minutes}m</strong><small>Training this week</small><i><b style="width:${Math.min(100,m.minutes/150*100)}%"></b></i></button></section><section class="section-block"><div class="section-title"><div><span class="eyebrow">NEXT ACTION</span><h2>Keep it simple</h2></div></div><div class="action-grid"><button data-page="workouts"><span>🏋️</span><strong>Choose a workout</strong><small>Filter by goal, time and equipment.</small></button><button data-page="hydration"><span>💧</span><strong>${remaining?`${remaining} ml to water goal`:"Water goal complete"}</strong><small>${remaining?"Small steps count.":"Nice work today."}</small></button><button data-page="nutrition"><span>🥗</span><strong>Log your food</strong><small>Keep today's nutrition visible.</small></button></div></section></main>`,"home");$("home-start")?.addEventListener("click",()=>openWorkout(workout.id));}

async function fetchWorkouts(){const rows=await safe(()=>db.from("workouts").select("*").order("id"),[]);return rows.length?rows:DEFAULT_WORKOUTS;}
function normalizeWorkout(w){return {...w,duration_minutes:Number(w.duration_minutes||20),level:w.level||"All levels",category:w.category||"Workout",description:w.description||"A focused workout for today.",icon:w.icon||"💪"};}
async function recommendedWorkout(){const all=(await fetchWorkouts()).map(normalizeWorkout);const p=prefs();const goal=String(profile.goal||"").toLowerCase();const level=String(profile.level||"").toLowerCase();const desiredMinutes=Number(p.duration)||30;const wanted=all.filter(w=>{const text=`${w.name} ${w.category} ${w.description}`.toLowerCase();const levelOk=!level||level.includes("consistency")||w.level.toLowerCase().includes(level)||w.level.toLowerCase().includes("all");const goalOk=goal.includes("weight")?/cardio|fat|conditioning/.test(text):goal.includes("muscle")||goal.includes("strong")?/strength|full|muscle/.test(text):true;return levelOk&&goalOk;});return (wanted.sort((a,b)=>Math.abs(Number(a.duration_minutes)-desiredMinutes)-Math.abs(Number(b.duration_minutes)-desiredMinutes))[0]||all[0]||DEFAULT_WORKOUTS[0]);}

async function workoutsPage(){const [all,rec]=await Promise.all([fetchWorkouts(),recommendedWorkout()]);const p=prefs();pageShell(`${header("WORKOUTS","Train with a plan.","Pick a session that fits your goal, time and equipment.")}<main><section class="section-block filter-panel"><div class="section-title"><div><span class="eyebrow">PERSONALIZE</span><h2>What fits today?</h2></div></div><div class="filter-grid"><label>Equipment<select id="equipment"><option>No equipment</option><option>Dumbbells</option><option>Resistance bands</option><option>Gym</option></select></label><label>Time<select id="duration"><option value="15">15 min</option><option value="20">20 min</option><option value="30">30 min</option><option value="45">45 min</option><option value="60">60 min</option></select></label></div><p class="form-help">Your workout recommendation uses these preferences on this device.</p></section><section class="section-block"><div class="section-title"><div><span class="eyebrow">RECOMMENDED</span><h2>For you</h2></div><span class="pill">${esc(p.duration)} min</span></div><button class="featured-workout" id="recommended-card"><div class="featured-icon">${rec.icon}</div><div><span class="eyebrow">${esc(rec.level)}</span><strong>${esc(rec.name)}</strong><p>${esc(rec.description)}</p><small>${rec.duration_minutes} min • ${esc(rec.category)}</small></div><b>Start →</b></button></section><section class="section-block"><div class="section-title"><h2>Workout library</h2><span>${all.length} sessions</span></div><div class="workout-list">${all.map(w=>`<button class="workout-card" data-workout-id="${esc(w.id)}"><div class="workout-icon">${w.icon||"💪"}</div><div><span class="eyebrow">${esc(w.level||"All levels")}</span><strong>${esc(w.name)}</strong><small>${Number(w.duration_minutes||0)} min • ${esc(w.category||"Workout")}</small><p>${esc(w.description||"Ready when you are.")}</p></div><b>›</b></button>`).join("")}</div></section></main>`,"workouts");$("equipment").value=p.equipment;$("duration").value=String(p.duration);$("equipment").onchange=()=>{setPrefs({equipment:$("equipment").value});workoutsPage();};$("duration").onchange=()=>{setPrefs({duration:Number($("duration").value)});workoutsPage();};$("recommended-card").onclick=()=>openWorkout(rec.id);app.querySelectorAll("[data-workout-id]").forEach(b=>b.onclick=()=>openWorkout(b.dataset.workoutId));}

function exerciseKey(name){return String(name||"").trim().toLowerCase();}function guideFor(e){return FALLBACK_EXERCISES[exerciseKey(e.name)]||FALLBACK_EXERCISES["bodyweight squat"];}function workSeconds(e){return Number(e.work_seconds||e.duration_seconds||(exerciseKey(e.name).includes("plank")?30:40));}function restSeconds(e){return Math.max(10,Number(e.rest_seconds||45));}function exerciseImage(e){return FALLBACK_EXERCISES[exerciseKey(e.name)]?.image||"/assets/exercises/bodyweight-squat.svg";}function exerciseArt(e,cls="exercise-art"){return `<div class="${cls}"><img src="${exerciseImage(e)}" alt="${esc(e.name)}" loading="lazy"><span>FORM GUIDE</span></div>`;}
async function workoutData(id){if(!/^\d+$/.test(String(id))){const base=DEFAULT_WORKOUTS.find(w=>String(w.id)===String(id))||DEFAULT_WORKOUTS[0];return{workout:normalizeWorkout(base),exercises:base.exercises.map((name,i)=>({id:`${id}-${i}`,name,sort_order:i,work_seconds:40,rest_seconds:45}))};}const [{data:workout,error:we},{data:exercises,error:ee}]=await Promise.all([db.from("workouts").select("*").eq("id",id).single(),db.from("workout_exercises").select("*").eq("workout_id",id).order("sort_order",{ascending:true})]);if(we||ee)throw(we||ee);return{workout:normalizeWorkout(workout),exercises:exercises||[]};}
async function openWorkout(id){try{const data=await workoutData(id);workoutContext={id,...data};workoutOverview();}catch(e){toastMsg(e.message||"Couldn't load that workout","error");}}
function workoutOverview(){const{workout,exercises}=workoutContext;pageShell(`${header("WORKOUT",esc(workout.name),`${workout.duration_minutes} min • ${esc(workout.level)}`,"MF")}<main><section class="workout-intro"><div><span class="eyebrow">${esc(workout.category)}</span><h2>${esc(workout.description)}</h2><div class="hero-meta"><span>⏱ ${workout.duration_minutes} min</span><span>🔁 ${exercises.length} exercises</span><span>🏠 ${esc(prefs().equipment)}</span></div></div><button class="primary-button" id="start-session">▶ Start workout</button></section><section class="section-block"><div class="section-title"><h2>Workout plan</h2><span>Preview</span></div>${exercises.map((e,i)=>`<button class="exercise-row" data-preview="${i}">${exerciseArt(e,"exercise-row-art")}<div><span class="eyebrow">${i+1} / ${exercises.length}</span><strong>${esc(e.name)}</strong><small>${workSeconds(e)} sec work • ${restSeconds(e)} sec rest</small></div><b>›</b></button>`).join("")}</section></main>`,"workouts");$("start-session").onclick=()=>showExercise(0);app.querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>showExercise(Number(b.dataset.preview)));}
function stopTimer(){if(timerId)clearInterval(timerId);timerId=null;}
function showExercise(index){stopTimer();const{exercises}=workoutContext;const e=exercises[index],guide=guideFor(e),total=workSeconds(e);let left=total;timerPaused=false;pageShell(`${header(`EXERCISE ${index+1} OF ${exercises.length}`,esc(e.name),"Focus on smooth, controlled movement.","MF")}<main><div class="session-progress"><i style="width:${Math.max(8,index/exercises.length*100)}%"></i></div>${exerciseArt(e,"exercise-feature")}<section class="timer-card"><span>WORK TIME</span><strong id="timer-value">${String(left).padStart(2,"0")}</strong><small>seconds</small><div class="timer-track"><i id="timer-bar"></i></div><div class="timer-actions"><button class="secondary-button" id="pause">Ⅱ Pause</button><button class="secondary-button" id="skip">Skip exercise</button></div></section><section class="section-block"><div class="section-title"><div><span class="eyebrow">HOW TO</span><h2>${esc(e.name)}</h2></div></div><div class="instruction-list">${guide.steps.map((s,n)=>`<div class="instruction"><b>${n+1}</b><span>${esc(s)}</span></div>`).join("")}</div><div class="tip-grid"><div class="tip"><strong>⚠ Common mistake</strong><span>${esc(guide.mistakes)}</span></div><div class="tip good"><strong>🌱 Make it easier</strong><span>${esc(guide.easy)}</span></div></div><div class="info-row"><strong>Muscles worked</strong><span>${esc(guide.muscles)}</span></div></section></main>`,"workouts");$("pause").onclick=()=>{timerPaused=!timerPaused;$("pause").textContent=timerPaused?"▶ Resume":"Ⅱ Pause";};$("skip").onclick=()=>nextStep(index);const tick=()=>{if(timerPaused)return;const val=$("timer-value"),bar=$("timer-bar");if(!val)return stopTimer();val.textContent=String(Math.max(0,left)).padStart(2,"0");bar.style.width=`${Math.max(0,left/total*100)}%`;if(left<=0){stopTimer();showRest(index);return;}left--;};tick();timerId=setInterval(tick,1000);}
function nextStep(index){stopTimer();index<workoutContext.exercises.length-1?showRest(index,true):finishWorkout();}
function showRest(index,skipped=false){stopTimer();const{exercises}=workoutContext;const next=exercises[index+1];let left=skipped?10:restSeconds(exercises[index]);pageShell(`${header("RECOVERY","Rest & reset",next?`Next: ${esc(next.name)}`:"You are at the finish line.","MF")}<main><section class="rest-screen"><div class="rest-ring"><strong id="rest-value">${String(left).padStart(2,"0")}</strong><small>sec</small></div><span class="eyebrow">BREATHE</span><h2>${next?"Next movement":"Workout complete"}</h2><p>${next?"Use this break to reset your breathing and get ready.":"Finish strong and save your session."}</p>${next?`<div class="next-card">${exerciseArt(next,"next-art")}<div><span class="eyebrow">NEXT</span><strong>${esc(next.name)}</strong><small>${workSeconds(next)} seconds</small></div></div>`:""}<button class="primary-button" id="rest-action">${next?"Skip rest & start next":"Finish workout"}</button></section></main>`,"workouts");$("rest-action").onclick=()=>{stopTimer();next?showExercise(index+1):finishWorkout();};const tick=()=>{const v=$("rest-value");if(!v)return stopTimer();v.textContent=String(Math.max(0,left)).padStart(2,"0");if(left<=0){stopTimer();next?showExercise(index+1):finishWorkout();return;}left--;};tick();timerId=setInterval(tick,1000);}
async function finishWorkout(){stopTimer();const{workout,exercises,id}=workoutContext;const duration=Math.max(1,Number(workout.duration_minutes||1));let error=null;if(/^\d+$/.test(String(id))){const r=await db.from("workout_logs").insert({user_id:user.id,workout_id:Number(id),completed_at:new Date().toISOString(),duration_minutes:duration,calories_burned:Math.round(duration*7)});error=r.error;}else{const r=await db.from("workout_logs").insert({user_id:user.id,completed_at:new Date().toISOString(),duration_minutes:duration,calories_burned:Math.round(duration*7)});error=r.error;}pageShell(`<main><section class="complete-card"><div class="complete-icon">✓</div><span class="eyebrow">WORKOUT COMPLETE</span><h1>Strong finish. 🎉</h1><p>${esc(workout.name)} is complete. The important part is that you showed up.</p><div class="stats"><div><strong>${duration}</strong><small>Minutes</small></div><div><strong>${Math.round(duration*7)}</strong><small>Calories*</small></div><div><strong>${exercises.length}</strong><small>Exercises</small></div></div>${error?`<p class="message error">Workout could not be saved. ${esc(error.message)}</p>`:`<p class="message success">Workout saved ✓</p>`}<button class="primary-button" id="done">Back to workouts</button></section></main>`,"workouts");$("done").onclick=workoutsPage;}

async function nutrition(){const m=await metrics();pageShell(`${header("NUTRITION","Fuel your body.","Track the basics without making food logging a second job.")}<main><section class="metric-grid two"><div><span>🔥</span><strong>${m.calories}</strong><small>Calories today</small></div><div><span>💪</span><strong>${m.protein}g</strong><small>Protein today</small></div></section><section class="section-block"><div class="section-title"><h2>Log a meal</h2><span>Quick entry</span></div><div class="form-card"><label>Meal name<input id="meal-name" maxlength="80" placeholder="Chicken and rice"></label><div class="form-grid"><label>Calories<input id="meal-calories" type="number" min="0" max="20000" inputmode="numeric" placeholder="500"></label><label>Protein (g)<input id="meal-protein" type="number" min="0" max="1000" inputmode="numeric" placeholder="30"></label></div><label>Meal type<select id="meal-type"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select></label><button class="primary-button" id="save-meal">Save meal</button></div></section><section class="section-block"><div class="section-title"><h2>Today's meals</h2><span>${m.meals.length}</span></div>${m.meals.length?m.meals.map(x=>`<div class="history-row"><span>🥗</span><div><strong>${esc(x.name)}</strong><small>${esc(x.meal_type||"Meal")} • ${Number(x.protein_g||0)}g protein</small></div><b>${Number(x.calories||0)} kcal</b><button class="delete-button" data-delete-meal="${x.id}" aria-label="Delete meal">×</button></div>`).join(""):`<div class="empty-card">Nothing logged yet. Add your first meal above.</div>`}</section></main>`,"nutrition");$("save-meal").onclick=async()=>{const name=$("meal-name").value.trim(),calories=Number($("meal-calories").value||0),protein=Number($("meal-protein").value||0);if(!name)return toastMsg("Enter a meal name","error");if(calories<0||protein<0)return toastMsg("Nutrition values cannot be negative","error");const r=await db.from("meal_logs").insert({user_id:user.id,name,calories,protein_g:protein,meal_type:$("meal-type").value,logged_at:new Date().toISOString()});if(r.error)toastMsg("Couldn't save meal: "+r.error.message,"error");else{toastMsg("Meal added ✓","success");nutrition();}};app.querySelectorAll("[data-delete-meal]").forEach(b=>b.onclick=async()=>{const r=await db.from("meal_logs").delete().eq("id",b.dataset.deleteMeal).eq("user_id",user.id);if(r.error)toastMsg("Couldn't remove meal","error");else nutrition();});}

async function hydration(){const m=await metrics(),pct=Math.min(100,m.water/2000*100),entries=await safe(()=>db.from("hydration_logs").select("id,amount_ml,logged_at").eq("user_id",user.id).gte("logged_at",startOfDay()).lte("logged_at",endOfDay()).order("logged_at",{ascending:false}),[]);pageShell(`${header("HYDRATION","Drink to perform.","A simple 2 litre daily target. Adjust it later as your needs change.")}<main><section class="water-hero"><div class="water-drop">💧</div><div><span class="eyebrow">TODAY</span><h2>${(m.water/1000).toFixed(2)} L</h2><p>${m.water>=2000?"Goal complete 🎉":`${((2000-m.water)/1000).toFixed(2)} L remaining`}</p></div></section><div class="big-progress"><i style="width:${pct}%"></i></div><div class="quick-water"><button data-water="250">+250 ml</button><button data-water="500">+500 ml</button><button data-water="750">+750 ml</button><button data-water="1000">+1 L</button></div><section class="section-block"><div class="section-title"><h2>Today's entries</h2><span>${Math.round(pct)}%</span></div>${entries.length?`<div class="history-list">${entries.map(x=>`<div class="history-row"><span>💧</span><div><strong>${x.amount_ml} ml</strong><small>${new Date(x.logged_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</small></div><button class="delete-button" data-delete-water="${x.id}">×</button></div>`).join("")}</div>`:`<div class="empty-card">No water logged yet. Start with 250 ml.</div>`}</section></main>`,"hydration");app.querySelectorAll("[data-water]").forEach(b=>b.onclick=async()=>{const amount=Number(b.dataset.water);const r=await db.from("hydration_logs").insert({user_id:user.id,amount_ml:amount,logged_at:new Date().toISOString()});if(r.error)toastMsg("Couldn't save water","error");else hydration();});app.querySelectorAll("[data-delete-water]").forEach(b=>b.onclick=async()=>{const r=await db.from("hydration_logs").delete().eq("id",b.dataset.deleteWater).eq("user_id",user.id);if(r.error)toastMsg("Couldn't remove entry","error");else hydration();});}

async function progress(){const[m,s]=await Promise.all([metrics(),streak()]);const last=m.workouts.slice(0,8);pageShell(`${header("PROGRESS","See your work.","Progress is consistency made visible.")}<main><section class="metric-grid"><div><span>🔥</span><strong>${s}</strong><small>Day streak</small></div><div><span>🏋️</span><strong>${m.workouts.length}</strong><small>Workouts this week</small></div><div><span>⏱️</span><strong>${m.minutes}m</strong><small>Training this week</small></div><div><span>🥗</span><strong>${m.protein}g</strong><small>Protein today</small></div></section><section class="section-block"><div class="section-title"><div><span class="eyebrow">CONSISTENCY</span><h2>Your week</h2></div><span>${m.workouts.length}/4 workouts</span></div><div class="week-bars">${[0,1,2,3,4,5,6].map(offset=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(d.getDay()===0?6:d.getDay()-1)+offset);const key=localDate(d);const done=m.workouts.some(w=>localDate(w.completed_at)===key);return `<div><i class="${done?"done":""}"></i><small>${d.toLocaleDateString([], {weekday:"narrow"})}</small></div>`}).join("")}</div></section><section class="section-block"><div class="section-title"><h2>Workout history</h2><span>${last.length} recent</span></div>${last.length?last.map(w=>`<div class="history-row"><span>🏋️</span><div><strong>${w.duration_minutes||0} min workout</strong><small>${new Date(w.completed_at).toLocaleDateString([], {month:"short",day:"numeric"})}</small></div><b>${w.calories_burned||0} kcal</b></div>`).join(""):`<div class="empty-card">Complete your first workout and your history will appear here.</div>`}</section></main>`,"progress");}

async function profilePage(){const[m,s]=await Promise.all([metrics(),streak()]);pageShell(`${header("PROFILE","Build your plan around you.","Your preferences shape recommendations.")}<main><section class="profile-hero"><div class="profile-avatar-large">${esc((profile.name||"M")[0]).toUpperCase()}</div><div><h2>${esc(profile.name||"Mike")}</h2><p>${esc(profile.goal||"Fitness journey")}</p><span class="eyebrow">${esc(profile.level||"Building consistency")}</span></div></section><section class="section-block"><div class="section-title"><h2>Your preferences</h2><span>Personalize</span></div><div class="form-card"><label>Display name<input id="profile-name" maxlength="60" value="${esc(profile.name||"")}"></label><label>Goal<select id="profile-goal"><option>Get stronger & feel energetic</option><option>Lose weight</option><option>Build muscle</option><option>Improve fitness</option></select></label><label>Fitness level<select id="profile-level"><option>Building consistency</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Training preference<select id="profile-preference"><option>Home workouts</option><option>Gym workouts</option><option>Outdoor workouts</option></select></label><button class="primary-button" id="save-profile">Save changes</button><button class="secondary-button" id="sign-out">Sign out</button></div></section><section class="section-block"><div class="section-title"><h2>Your snapshot</h2><span>Today</span></div><div class="metric-grid"><div><span>🔥</span><strong>${s}</strong><small>Day streak</small></div><div><span>💧</span><strong>${(m.water/1000).toFixed(1)}L</strong><small>Water</small></div><div><span>🏋️</span><strong>${m.workouts.length}</strong><small>Week workouts</small></div><div><span>🥗</span><strong>${m.calories}</strong><small>Calories</small></div></div></section></main>`,"profile");$("profile-goal").value=profile.goal||"Get stronger & feel energetic";$("profile-level").value=profile.level||"Building consistency";$("profile-preference").value=profile.preference||"Home workouts";$("save-profile").onclick=async()=>{const next={id:user.id,name:$("profile-name").value.trim(),goal:$("profile-goal").value,level:$("profile-level").value,preference:$("profile-preference").value};if(!next.name)return toastMsg("Enter your name","error");const r=await db.from("profiles").upsert(next,{onConflict:"id"});if(r.error)toastMsg("Couldn't save profile: "+r.error.message,"error");else{profile={...profile,...next};toastMsg("Profile updated ✓","success");profilePage();}};$("sign-out").onclick=async()=>{await db.auth.signOut();user=null;showAuth();};}

async function render(page){if(!user)return showAuth();if(page==="home")return home();if(page==="workouts")return workoutsPage();if(page==="nutrition")return nutrition();if(page==="hydration")return hydration();if(page==="progress")return progress();if(page==="profile")return profilePage();return home();}
window.render=render;

function setAuthBusy(busy){authSubmitButton.disabled=busy;authSubmitButton.textContent=busy?(signupMode?"Creating…":"Signing in…"):(signupMode?"Create account":"Sign in");}
async function authSubmit(e){e?.preventDefault();if(authSubmit.busy)return;authSubmit.busy=true;setAuthBusy(true);if(authMessage)authMessage.textContent="";try{const email=$("auth-email").value.trim(),password=$("auth-password").value,name=$("auth-name")?.value.trim()||"";if(!email||!password)throw new Error("Enter your email and password");if(signupMode&&!name)throw new Error("Enter your name");let result;if(signupMode){result=await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname,data:{name}}});if(result.error)throw result.error;if(!result.data.user)throw new Error("Account creation did not return a user");if(!result.data.session){if(authMessage){authMessage.className="message success";authMessage.textContent="Account created. Check your email to verify your account, then sign in.";}return;}await enterApp(result.data.user);return;}result=await db.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(!result.data.session||!result.data.user)throw new Error("Sign-in succeeded but no active session was returned. Please try again.");await enterApp(result.data.user);}catch(e){if(authMessage){authMessage.className="message error";authMessage.textContent=e.message||"Authentication failed";}}finally{authSubmit.busy=false;setAuthBusy(false);}}

authToggle.onclick=()=>{signupMode=!signupMode;authName.classList.toggle("hidden",!signupMode);authTitle.textContent=signupMode?"Create your account":"Welcome back 👋";authSubtitle.textContent=signupMode?"Start with a simple fitness plan.":"Sign in to continue your fitness journey.";authToggle.textContent=signupMode?"Already have an account? Sign in":"Need an account? Sign up";setAuthBusy(false);authMessage.textContent="";};
authForm.onsubmit=authSubmit;

db.auth.onAuthStateChange((event,session)=>{if(session?.user){user=session.user;if(!booted) return;}else if(event==="SIGNED_OUT"){user=null;showAuth();}});

(async()=>{try{const{data}=await db.auth.getSession();if(data.session?.user){user=data.session.user;await loadProfile();await recordLogin();booted=true;showApp();}else{booted=true;showAuth();}}catch(e){booted=true;showAuth("Could not restore your session. Please sign in again.");}})();
