(()=>{
 const baseRender=window.render;
 const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
 const dayKey=()=>new Date().toISOString().slice(0,10);
 const todayStart=()=>dayKey()+"T00:00:00.000Z";
 const tomorrow=()=>{const d=new Date();d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)+"T00:00:00.000Z"};
 const currency=n=>Number(n||0).toLocaleString();
 const safe=async(fn,fallback)=>{try{const r=await fn();return r.error?fallback:r.data??fallback}catch{return fallback}};
 function bind(){app.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>window.render(b.dataset.page));}
 async function nutrition(){
  const meals=await safe(()=>supabase.from("meal_logs").select("id,name,calories,protein_g,meal_type,logged_at").eq("user_id",user.id).gte("logged_at",todayStart()).lt("logged_at",tomorrow()).order("logged_at",{ascending:false}),[]);
  const calories=meals.reduce((a,m)=>a+Number(m.calories||0),0), protein=meals.reduce((a,m)=>a+Number(m.protein_g||0),0);
  app.innerHTML=`<header><div><small>NUTRITION</small><h1>Fuel your body 🥗</h1></div><div class="avatar">${(profile.name||"M")[0].toUpperCase()}</div></header><main><section class="hero"><span>TODAY</span><h2>${currency(calories)} kcal</h2><p>${currency(protein)}g protein logged today. Keep meals simple and consistent.</p></section><section class="stats"><div>🔥<strong>${currency(calories)}</strong><small>Calories</small></div><div>💪<strong>${currency(protein)}g</strong><small>Protein</small></div><div>🍽️<strong>${meals.length}</strong><small>Meals</small></div></section><section><div class="section-title"><h2>Log a meal</h2><span>Today</span></div><div class="form-card"><label>Meal name<input id="meal-name" placeholder="Chicken and rice"></label><label>Meal type<select id="meal-type"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select></label><label>Calories<input id="meal-calories" type="number" min="0" placeholder="500"></label><label>Protein (g)<input id="meal-protein" type="number" min="0" placeholder="30"></label><button class="primary-button" id="save-meal">Add meal</button></div></section><section><div class="section-title"><h2>Today's meals</h2><span>${meals.length} logged</span></div>${meals.length?meals.map(m=>`<div class="task"><div class="check">🥗</div><div><strong>${esc(m.name)}</strong><small>${esc(m.meal_type||"Meal")} • ${currency(m.calories)} kcal • ${currency(m.protein_g)}g protein</small></div><button class="delete-meal" data-id="${m.id}" style="margin-left:auto;border:0;background:transparent;color:#ff6b7f;font-size:20px">×</button></div>`).join(""):'<div class="task"><div><strong>No meals logged yet</strong><small>Add your first meal above.</small></div></div>'}</section></main>${nav("nutrition")}`;bind();
  $("save-meal").onclick=async()=>{const name=$("meal-name").value.trim();if(!name)return toastMsg("Enter a meal name");const r=await supabase.from("meal_logs").insert({user_id:user.id,name,calories:Number($("meal-calories").value||0),protein_g:Number($("meal-protein").value||0),meal_type:$("meal-type").value,logged_at:new Date().toISOString()});if(r.error)toastMsg(r.error.message);else{toastMsg("Meal added ✓");nutrition()}};
  app.querySelectorAll(".delete-meal").forEach(b=>b.onclick=async()=>{const r=await supabase.from("meal_logs").delete().eq("id",b.dataset.id).eq("user_id",user.id);toastMsg(r.error?r.error.message:"Meal removed");nutrition()});
 }
 async function hydration(){
  const rows=await safe(()=>supabase.from("hydration_logs").select("id,amount_ml,logged_at").eq("user_id",user.id).gte("logged_at",todayStart()).lt("logged_at",tomorrow()).order("logged_at",{ascending:false}),[]);
  const total=rows.reduce((a,r)=>a+Number(r.amount_ml||0),0),goal=2000,pct=Math.min(100,Math.round(total/goal*100));
  app.innerHTML=`<header><div><small>HYDRATION</small><h1>Stay hydrated 💧</h1></div><div class="avatar">${(profile.name||"M")[0].toUpperCase()}</div></header><main><section class="hero"><span>TODAY'S GOAL</span><h2>${(total/1000).toFixed(1)}L / ${(goal/1000).toFixed(1)}L</h2><p>${pct}% complete. Aim for steady sips throughout the day.</p><div class="progress"><i style="width:${pct}%"></i></div></section><section><div class="section-title"><h2>Add water</h2><span>Quick log</span></div><div class="quick-grid">${[250,500,750,1000].map(x=>`<button data-water="${x}">💧<strong>${x>=1000?"1L":x+"ml"}</strong><small>Add water</small></button>`).join("")}</div></section><section><div class="section-title"><h2>Today's log</h2><span>${rows.length} entries</span></div>${rows.length?rows.map(r=>`<div class="task"><div class="check">💧</div><div><strong>${Number(r.amount_ml)} ml</strong><small>${new Date(r.logged_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</small></div><button class="delete-water" data-id="${r.id}" style="margin-left:auto;border:0;background:transparent;color:#ff6b7f;font-size:20px">×</button></div>`).join(""):'<div class="task"><div><strong>No water logged yet</strong><small>Start with a glass.</small></div></div>'}</section></main>${nav("hydration")}`;bind();
  app.querySelectorAll("[data-water]").forEach(b=>b.onclick=async()=>{const r=await supabase.from("hydration_logs").insert({user_id:user.id,amount_ml:Number(b.dataset.water),logged_at:new Date().toISOString()});if(r.error)toastMsg(r.error.message);else{toastMsg("Water logged 💧");hydration()}});app.querySelectorAll(".delete-water").forEach(b=>b.onclick=async()=>{const r=await supabase.from("hydration_logs").delete().eq("id",b.dataset.id).eq("user_id",user.id);toastMsg(r.error?r.error.message:"Water entry removed");hydration()});
 }
 async function progress(){
  const [workouts,meals,water]=await Promise.all([safe(()=>supabase.from("workout_logs").select("id,workout_id,duration_minutes,calories_burned,completed_at").eq("user_id",user.id).order("completed_at",{ascending:false}),[]),safe(()=>supabase.from("meal_logs").select("id,calories,protein_g,logged_at").eq("user_id",user.id).gte("logged_at",todayStart()).lt("logged_at",tomorrow()),[]),safe(()=>supabase.from("hydration_logs").select("amount_ml,logged_at").eq("user_id",user.id).gte("logged_at",todayStart()).lt("logged_at",tomorrow()),[])]);
  const mins=workouts.reduce((a,r)=>a+Number(r.duration_minutes||0),0),burn=workouts.reduce((a,r)=>a+Number(r.calories_burned||0),0),waterTotal=water.reduce((a,r)=>a+Number(r.amount_ml||0),0),cal=meals.reduce((a,r)=>a+Number(r.calories||0),0),prot=meals.reduce((a,r)=>a+Number(r.protein_g||0),0);
  app.innerHTML=`<header><div><small>PROGRESS</small><h1>Your journey 📈</h1></div><div class="avatar">${(profile.name||"M")[0].toUpperCase()}</div></header><main><section class="hero"><span>YOUR DATA</span><h2>Keep showing up.</h2><p>Your progress is built from the workouts, meals and water you actually log.</p></section><section class="stats"><div>🔥<strong>${loginStreak}</strong><small>Day streak</small></div><div>🏋️<strong>${workouts.length}</strong><small>Workouts</small></div><div>⏱️<strong>${mins}</strong><small>Workout mins</small></div><div>🔥<strong>${burn}</strong><small>Calories burned</small></div><div>💧<strong>${(waterTotal/1000).toFixed(1)}L</strong><small>Water today</small></div><div>🥗<strong>${cal}</strong><small>Calories today</small></div></section><section><div class="section-title"><h2>Nutrition today</h2><span>${prot}g protein</span></div><div class="task"><div class="check">🥗</div><div><strong>${currency(cal)} kcal</strong><small>${currency(prot)}g protein from ${meals.length} meals</small></div></div></section><section><div class="section-title"><h2>Recent workouts</h2><span>${workouts.length} total</span></div>${workouts.slice(0,5).map(w=>`<div class="task"><div class="check">✓</div><div><strong>Workout completed</strong><small>${new Date(w.completed_at).toLocaleDateString()} • ${w.duration_minutes||0} min • ${w.calories_burned||0} kcal</small></div></div>`).join("")||'<div class="task"><div><strong>No completed workouts yet</strong><small>Start your first session from Workouts.</small></div></div>'}</section></main>${nav("progress")}`;bind();
 }
 const old=window.render;window.render=page=>{if(page==="nutrition")return nutrition();if(page==="hydration")return hydration();if(page==="progress")return progress();return old(page)};
 window.mikefitRefreshData=()=>{try{const p=document.querySelector("nav .active small")?.textContent.toLowerCase();if(p)window.render(p)}catch{}};
})();