(()=>{
 const originalRender=window.render;
 const sprite="/assets/exercises/illustrations.svg#";
 const guides={
  "bodyweight squat":{id:"squat",steps:["Stand with your feet about shoulder-width apart.","Push your hips back as if sitting into a chair.","Bend your knees and lower comfortably.","Drive through your feet to stand tall."],mistakes:"Knees collapsing inward or rushing the movement.",easy:"Use a chair behind you as a target and reduce the depth.",muscles:"Glutes, thighs and core."},
  "incline push-up":{id:"incline-pushup",steps:["Place your hands on a sturdy raised surface.","Keep your body straight from head to heels.","Bend your elbows and lower your chest.","Push the surface away to return."],mistakes:"Hips sagging or elbows flaring too far out.",easy:"Use a wall or a higher counter.",muscles:"Chest, shoulders, arms and core."},
  "glute bridge":{id:"glute-bridge",steps:["Lie on your back with knees bent and feet flat.","Keep your arms relaxed beside you.","Squeeze your glutes and lift your hips.","Pause, then lower slowly."],mistakes:"Over-arching the lower back or pushing from the toes.",easy:"Lift your hips only part way if needed.",muscles:"Glutes, hamstrings and core."},
  "plank":{id:"plank",steps:["Place your forearms under your shoulders.","Extend your legs and brace your stomach.","Keep your body in one straight line.","Breathe normally while holding."],mistakes:"Hips sagging, hips too high or holding your breath.",easy:"Put your knees on the floor while keeping a straight line.",muscles:"Core, shoulders and glutes."},
  "dead bug":{id:"dead-bug",steps:["Lie on your back with arms up and knees bent.","Gently brace your stomach.","Extend one arm and the opposite leg slowly.","Return and switch sides."],mistakes:"Letting your lower back lift from the floor.",easy:"Move only your arms first, then add your legs.",muscles:"Deep core and hip muscles."},
  "bird dog":{id:"bird-dog",steps:["Start on your hands and knees.","Reach one arm forward and the opposite leg back.","Pause while keeping your hips level.","Return and switch sides."],mistakes:"Twisting or lifting the leg too high.",easy:"Lift only one arm or one leg at a time.",muscles:"Core, back, shoulders and glutes."},
  "side plank":{id:"side-plank",steps:["Lie on your side with your forearm under your shoulder.","Stack or stagger your feet.","Lift your hips into a straight line.","Hold while breathing normally."],mistakes:"Letting your hips drop or shoulders roll forward.",easy:"Keep your bottom knee on the floor.",muscles:"Core, shoulders and hips."},
  "reverse lunges":{id:"reverse-lunges",steps:["Stand tall with your feet comfortable apart.","Step one foot backward.","Bend both knees comfortably.","Push through the front foot to return."],mistakes:"Front knee collapsing inward or unstable steps.",easy:"Hold a wall or chair and take a smaller step.",muscles:"Glutes, thighs and calves."},
  "calf raises":{id:"calf-raises",steps:["Stand tall with feet about hip-width apart.","Rise slowly onto the balls of your feet.","Pause at the top.","Lower your heels with control."],mistakes:"Bouncing or rolling the ankles outward.",easy:"Hold a wall or chair for balance.",muscles:"Calves and ankles."},
  "march in place":{id:"march-in-place",steps:["Stand tall with your feet under your hips.","Lift one knee comfortably.","Lower softly and lift the other knee.","Keep a steady rhythm."],mistakes:"Leaning backward or stomping down.",easy:"Lift your knees lower and slow the pace.",muscles:"Legs, hips and cardiovascular system."},
  "jumping jacks":{id:"jumping-jacks",steps:["Start with feet together and arms by your sides.","Jump feet apart while raising your arms.","Land softly with knees slightly bent.","Return to the start."],mistakes:"Hard landings or locking the knees.",easy:"Step one foot out at a time instead of jumping.",muscles:"Legs, shoulders and cardiovascular system."},
  "high knees":{id:"high-knees",steps:["Stand tall and brace your stomach gently.","Drive one knee upward.","Lower softly and switch legs.","Pump your arms naturally."],mistakes:"Stomping or leaning too far backward.",easy:"March slowly and lift knees only as high as comfortable.",muscles:"Legs, hips and cardiovascular system."}
 };
 const guideFor=e=>guides[String(e.name||"").trim().toLowerCase()]||guides["bodyweight squat"];
 const workSeconds=e=>Number(e.work_seconds||e.duration_seconds||((String(e.name||"").toLowerCase().includes("plank"))?30:40));
 const restSeconds=e=>Math.max(1,Number(e.rest_seconds||45));
 const navTo=page=>{if(typeof originalRender==='function')originalRender(page)};
 const bindNav=()=>app.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>navTo(b.dataset.page));
 const illustration=(g,cls="exercise-illustration")=>`<svg class="${cls}" viewBox="0 0 400 240" role="img" aria-label="Exercise illustration"><use href="${sprite}${g.id}"></use></svg>`;
 window.render=page=>{if(page!=="workouts")return originalRender(page);renderLibrary()};
 async function renderLibrary(){app.innerHTML=`<header><div><small>WORKOUTS</small><h1>Let's get moving 💪</h1></div><div class="avatar">${(profile.name||"M")[0].toUpperCase()}</div></header><main><section class="hero"><span>MIKEFIT LIBRARY</span><h2>Choose your workout</h2><p>Every workout includes a human-style picture guide, simple instructions, timed exercises and rest.</p></section><section><div id="workout-list"><p>Loading workouts…</p></div></section></main>${nav("workouts")}`;bindNav();const {data,error}=await supabase.from("workouts").select("*").order("id");const box=$("workout-list");if(error){box.innerHTML=`<div class="task"><div><strong>Couldn't load workouts</strong><small>${error.message}</small></div></div>`;return}if(!data?.length){box.innerHTML='<div class="task"><div><strong>No workouts available yet.</strong></div></div>';return}box.innerHTML=data.map(w=>`<button class="task task-button workout-card" data-workout="${w.id}"><div class="check">${w.icon||"🏋️"}</div><div><strong>${w.name}</strong><small>${w.duration_minutes||0} min • ${w.level||"All levels"} • ${w.category||"Workout"}</small><small>${w.description||"Ready when you are."}</small></div><span>›</span></button>`).join("");box.querySelectorAll("[data-workout]").forEach(b=>b.onclick=()=>openWorkout(Number(b.dataset.workout)))}
 async function openWorkout(id){const [{data:w,error:we},{data:ex,error:ee}]=await Promise.all([supabase.from("workouts").select("*").eq("id",id).single(),supabase.from("workout_exercises").select("*").eq("workout_id",id).order("sort_order")]);if(we||ee){toastMsg((we||ee).message);return}const exercises=ex||[];let timer=null;
 const stopTimer=()=>{if(timer){clearInterval(timer);timer=null}};
 const text=e=>e.duration_seconds?`${e.duration_seconds}s`:e.sets&&e.reps?`${e.sets} sets × ${e.reps} reps`:"Move with control";
 const overview=()=>{stopTimer();app.innerHTML=`<header><button class="secondary-button back-small" id="back-library">‹</button><div class="avatar">${w.icon||"🏋️"}</div></header><main><section class="hero"><span>${w.level||"BEGINNER"}</span><h2>${w.name}</h2><p>${w.description||"A complete workout with simple exercise guidance."}</p><button class="primary-button" id="start-session">▶ Start Workout</button></section><section><div class="section-title"><h2>Workout Overview</h2><span>${exercises.length} exercises</span></div><div class="task"><div class="check">✓</div><div><strong>${w.duration_minutes||0} minutes</strong><small>40s work • 45s rest • Auto-advance</small></div></div></section><section><h2>Exercises</h2>${exercises.map((e,i)=>{const g=guideFor(e);return `<button class="task task-button" data-preview="${i}">${illustration(g,"exercise-thumb")}<div><strong>${i+1}. ${e.name}</strong><small>Work ${workSeconds(e)}s${e.rest_seconds?` • Rest ${e.rest_seconds}s`:" • Rest 45s"}</small></div><span>›</span></button>`}).join("")}</section></main>${nav("workouts")}`;bindNav();$("back-library").onclick=renderLibrary;$("start-session").onclick=()=>showExercise(0);app.querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>showExercise(Number(b.dataset.preview)))};
 function showExercise(i){stopTimer();const e=exercises[i],g=guideFor(e),total=workSeconds(e);let left=total,paused=false;app.innerHTML=`<header><button class="secondary-button back-small" id="back-overview">‹</button><div><strong>${i+1}. ${e.name}</strong><small class="header-step">${i+1} / ${exercises.length}</small></div></header><main><div class="workout-progress"><i style="width:${Math.max(8,((i)/exercises.length)*100)}%"></i></div><section class="exercise-hero">${illustration(g)}</section><div class="exercise-title-row"><h2>${e.name}</h2><span class="step-badge">${i+1} / ${exercises.length}</span></div><section><div class="work-timer-card"><span>TIME LEFT</span><strong id="exercise-time">${String(left).padStart(2,"0")}</strong><small>seconds • ${i+1} of ${exercises.length}</small><div class="timer-track"><i id="exercise-time-bar"></i></div></div><div class="timer-actions"><button class="secondary-button" id="pause-exercise">Ⅱ Pause</button><button class="primary-button" id="finish-early">Finish Early</button></div><h2>How to do it</h2><div class="instruction-list">${g.steps.map((s,n)=>`<div class="instruction"><b>${n+1}</b><span>${s}</span></div>`).join("")}</div><div class="tip-grid"><div class="tip danger"><strong>⚠ Common Mistakes</strong><span>${g.mistakes}</span></div><div class="tip good"><strong>🌱 Beginner Option</strong><span>${g.easy}</span></div></div><div class="task muscles"><div class="check">🎯</div><div><strong>Muscles Worked</strong><small>${g.muscles}</small></div></div></section></main>${nav("workouts")}`;bindNav();$("back-overview").onclick=overview;const tick=()=>{if(paused)return;$("exercise-time").textContent=String(left).padStart(2,"0");$("exercise-time-bar").style.width=Math.max(0,Math.round(left/total*100))+"%";if(left<=0){stopTimer();showRest(i);return}left--};$("pause-exercise").onclick=()=>{paused=!paused;$("pause-exercise").textContent=paused?"▶ Resume":"Ⅱ Pause"};$("finish-early").onclick=()=>{stopTimer();showRest(i)};tick();timer=setInterval(tick,1000)}
 function showRest(doneIndex){stopTimer();const next=exercises[doneIndex+1],rest=restSeconds(exercises[doneIndex]);let left=rest;const g=next?guideFor(next):null;app.innerHTML=`<header><button class="secondary-button back-small" id="rest-back">‹</button><strong>Rest Time</strong><span>${next?"NEXT":"DONE"}</span></header><main><section class="rest-screen"><div class="rest-ring" id="rest-ring" style="--rest-progress:100%"><div class="rest-ring-content"><strong id="rest-value">${String(left).padStart(2,"0")}</strong><small>seconds</small></div></div><h2>Catch your breath</h2><p style="color:var(--muted)">${next?"Your next exercise is ready below.":"You've completed every exercise."}</p>${next?`<div class="next-card next-exercise-card">${illustration(g,"next-exercise-art")}<div><strong>Next Exercise</strong><small>${next.name}</small><small>Work ${workSeconds(next)} seconds</small></div></div>`:`<div class="next-card"><div class="check">✓</div><div><strong>Final exercise complete</strong><small>Great work — finish the session.</small></div></div>`}<button class="primary-button" id="skip-rest">${next?"Skip Rest & Start Next":"Finish Workout"}</button></section></main>${nav("workouts")}`;bindNav();$("rest-back").onclick=()=>showExercise(doneIndex);const update=()=>{const pct=Math.round(left/rest*100);$("rest-value").textContent=String(left).padStart(2,"0");$("rest-ring").style.setProperty("--rest-progress",pct+"%");if(left<=0){stopTimer();next?showExercise(doneIndex+1):finishWorkout();return}left--};$("skip-rest").onclick=()=>{stopTimer();next?showExercise(doneIndex+1):finishWorkout()};update();timer=setInterval(update,1000)}
 async function finishWorkout(){stopTimer();const duration=Math.max(1,Number(w.duration_minutes||Math.ceil(exercises.reduce((a,e)=>a+workSeconds(e)+restSeconds(e),0)/60)));const r=await supabase.from("workout_logs").insert({user_id:user.id,workout_id:id,completed_at:new Date().toISOString(),duration_minutes:duration,calories_burned:Math.round(duration*7)});app.innerHTML=`<main><section class="hero complete-card"><div class="complete-icon">✓</div><span>WORKOUT COMPLETE</span><h2>Great job! 🎉</h2><p>You finished ${w.name}. That's another step forward.</p><div class="stats"><div>⏱️<strong>${duration} min</strong><small>Duration</small></div><div>🔥<strong>${Math.round(duration*7)}</strong><small>Calories</small></div><div>✓<strong>${exercises.length}/${exercises.length}</strong><small>Exercises</small></div></div>${r.error?`<p class="message error">Workout wasn't saved: ${r.error.message}</p>`:'<p class="message">Workout saved successfully ✓</p>'}<button class="primary-button" id="done-back">Back to Workouts</button></section></main>${nav("workouts")}`;bindNav();$("done-back").onclick=renderLibrary}
 overview();
 }
})();