(()=>{
 const originalRender=window.render;
 const guides={
  "bodyweight squat":{image:"assets/exercises/bodyweight-squat.svg",steps:["Stand with your feet about shoulder-width apart.","Push your hips backward like you're sitting on a chair.","Bend your knees and lower until comfortable.","Push through your feet to stand back up."],mistakes:"Knees collapsing inward or rushing the movement.",easy:"Use a chair behind you as a target and squat only as low as comfortable.",muscles:"Glutes, thighs and core."},
  "incline push-up":{image:"assets/exercises/incline-pushup.svg",steps:["Place your hands on a sturdy raised surface.","Keep your body straight from head to heels.","Bend your elbows and lower your chest toward the surface.","Push back to the starting position."],mistakes:"Hips sagging or elbows flaring too far out.",easy:"Use a wall or a higher counter if needed.",muscles:"Chest, shoulders, arms and core."},
  "glute bridge":{image:"assets/exercises/glute-bridge.svg",steps:["Lie on your back with knees bent and feet flat.","Keep your arms relaxed by your sides.","Squeeze your glutes and lift your hips.","Pause briefly, then lower slowly."],mistakes:"Over-arching the lower back or pushing from the toes.",easy:"Use a smaller range of motion.",muscles:"Glutes, hamstrings and core."},
  "plank":{image:"assets/exercises/plank.svg",steps:["Place your forearms under your shoulders.","Extend your legs and brace your stomach.","Keep your body in one straight line.","Breathe normally while holding the position."],mistakes:"Hips sagging, hips too high or holding your breath.",easy:"Put your knees on the floor while keeping a straight line from knees to head.",muscles:"Core, shoulders and glutes."},
  "dead bug":{image:"assets/exercises/dead-bug.svg",steps:["Lie on your back with arms up and knees bent.","Brace your stomach gently.","Extend one arm and the opposite leg slowly.","Return and switch sides."],mistakes:"Letting your lower back lift away from the floor.",easy:"Move only your arms first, then add the legs.",muscles:"Deep core and hip muscles."},
  "bird dog":{image:"assets/exercises/bird-dog.svg",steps:["Start on your hands and knees.","Reach one arm forward and the opposite leg back.","Pause while keeping your hips level.","Return and switch sides."],mistakes:"Twisting or lifting the leg too high.",easy:"Lift only one arm or one leg at a time.",muscles:"Core, back, shoulders and glutes."},
  "side plank":{image:"assets/exercises/side-plank.svg",steps:["Lie on your side with your forearm under your shoulder.","Stack or stagger your feet.","Lift your hips into a straight line.","Hold while breathing normally."],mistakes:"Letting the hips drop or shoulders roll forward.",easy:"Keep your bottom knee on the floor.",muscles:"Core, shoulders and hips."},
  "reverse lunges":{image:"assets/exercises/reverse-lunge.svg",steps:["Stand tall with feet comfortable apart.","Step one foot backward.","Bend both knees as far as comfortable.","Push through the front foot to return."],mistakes:"Front knee collapsing inward or taking an unstable step.",easy:"Hold a wall or chair for balance and take a smaller step.",muscles:"Glutes, thighs and calves."},
  "calf raises":{image:"assets/exercises/calf-raises.svg",steps:["Stand tall with feet about hip-width apart.","Slowly rise onto the balls of your feet.","Pause at the top.","Lower your heels with control."],mistakes:"Bouncing or rolling the ankles outward.",easy:"Hold a wall or chair for balance.",muscles:"Calves and ankles."},
  "march in place":{image:"assets/exercises/march-in-place.svg",steps:["Stand tall with your feet under your hips.","Lift one knee comfortably.","Lower it softly and lift the other knee.","Keep a steady, comfortable rhythm."],mistakes:"Leaning backward or stomping down.",easy:"Lift your knees lower and slow the pace.",muscles:"Legs, hips and cardiovascular system."},
  "jumping jacks":{image:"assets/exercises/jumping-jacks.svg",steps:["Start with your feet together and arms by your sides.","Jump your feet apart while raising your arms.","Land softly with knees slightly bent.","Return to the starting position."],mistakes:"Hard landings or locking the knees.",easy:"Step one foot out at a time instead of jumping.",muscles:"Legs, shoulders and cardiovascular system."},
  "high knees":{image:"assets/exercises/high-knees.svg",steps:["Stand tall and brace your stomach gently.","Drive one knee upward.","Lower softly and switch legs.","Pump your arms naturally and keep a steady rhythm."],mistakes:"Stomping or leaning too far backward.",easy:"March slowly and lift the knees only as high as comfortable.",muscles:"Legs, hips and cardiovascular system."}
 };
 const guideFor=e=>guides[String(e.name||"").trim().toLowerCase()]||{image:"assets/exercises/bodyweight-squat.svg",steps:["Move slowly and stay controlled.","Keep your breathing steady.","Use a comfortable range of motion.","Stop if you feel sharp pain."],mistakes:"Rushing or losing control of your posture.",easy:"Reduce the range or slow the movement.",muscles:"Whole body."};
 const navTo=page=>{if(typeof originalRender==='function')originalRender(page)};
 function bindNav(){app.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>navTo(b.dataset.page))}
 window.render=function(page){if(page!=="workouts")return originalRender(page);renderLibrary()};
 async function renderLibrary(){app.innerHTML=`<header><div><small>WORKOUTS</small><h1>Let's get moving 💪</h1></div><div class="avatar">${(profile.name||"M")[0].toUpperCase()}</div></header><main><section class="hero"><span>MIKEFIT LIBRARY</span><h2>Choose your workout</h2><p>Every workout includes a picture guide, simple instructions and rest between exercises.</p></section><section><div id="workout-list"><p>Loading workouts…</p></div></section></main>${nav("workouts")}`;bindNav();const {data,error}=await supabase.from("workouts").select("*").order("id");const box=$("workout-list");if(error){box.innerHTML=`<div class="task"><div><strong>Couldn't load workouts</strong><small>${error.message}</small></div></div>`;return}if(!data?.length){box.innerHTML='<div class="task"><div><strong>No workouts available yet.</strong></div></div>';return}box.innerHTML=data.map(w=>`<button class="task task-button workout-card" data-workout="${w.id}"><div class="check">${w.icon||"🏋️"}</div><div><strong>${w.name}</strong><small>${w.duration_minutes||0} min • ${w.level||"All levels"} • ${w.category||"Workout"}</small><small>${w.description||"Ready when you are."}</small></div><span>›</span></button>`).join("");box.querySelectorAll("[data-workout]").forEach(b=>b.onclick=()=>openWorkout(Number(b.dataset.workout)))}
 async function openWorkout(id){const [{data:w,error:we},{data:ex,error:ee}]=await Promise.all([supabase.from("workouts").select("*").eq("id",id).single(),supabase.from("workout_exercises").select("*").eq("workout_id",id).order("sort_order")]);if(we||ee){toastMsg((we||ee).message);return}const exercises=ex||[];let index=-1;let seconds=0,timer=null;const stopTimer=()=>{if(timer){clearInterval(timer);timer=null}};const text=e=>e.duration_seconds?`${e.duration_seconds} seconds`:e.sets&&e.reps?`${e.sets} sets × ${e.reps} reps`:"Move at your own pace";
 const overview=()=>{app.innerHTML=`<header><button class="secondary-button" style="width:auto;margin:0;padding:9px 13px" id="back-library">‹</button><div class="avatar">${w.icon||"🏋️"}</div></header><main><section class="hero"><span>${w.level||"BEGINNER"}</span><h2>${w.name}</h2><p>${w.description||"A complete workout with simple exercise guidance."}</p><button class="primary-button" id="start-session">▶ Start Workout</button></section><section><div class="section-title"><h2>Workout Overview</h2><span>${exercises.length} exercises</span></div><div class="task"><div class="check">✓</div><div><strong>${w.duration_minutes||0} minutes</strong><small>Pictures + instructions • Rest between exercises</small></div></div></section><section><h2>Exercises</h2>${exercises.map((e,i)=>{const g=guideFor(e);return `<button class="task task-button" data-preview="${i}"><img src="${g.image}" style="width:68px;height:56px;object-fit:contain;background:#f4f5f6;border-radius:10px" alt="${e.name}"><div><strong>${i+1}. ${e.name}</strong><small>${text(e)}${e.rest_seconds?` • Rest ${e.rest_seconds}s`:" • Rest 45s"}</small></div><span>›</span></button>`}).join("")}</section></main>${nav("workouts")}`;bindNav();$("back-library").onclick=renderLibrary;$("start-session").onclick=()=>showExercise(0);app.querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>showExercise(Number(b.dataset.preview)));};
 function showExercise(i){stopTimer();index=i;const e=exercises[index],g=guideFor(e),target=text(e),progress=((index)/exercises.length)*100;app.innerHTML=`<header><button class="secondary-button" style="width:auto;margin:0;padding:9px 13px" id="back-session">‹</button><div><strong>${index+1}. ${e.name}</strong><small style="display:block;color:var(--muted);text-align:right">${index+1} / ${exercises.length}</small></div></header><main><div class="workout-progress"><i style="width:${Math.max(6,progress)}%"></i></div><section class="exercise-hero"><img class="exercise-illustration" src="${g.image}" alt="Pictorial guide for ${e.name}"></section><div class="exercise-title-row"><h2>${e.name}</h2><span class="step-badge">${target}</span></div><section><h2>How to do it</h2><div class="instruction-list">${g.steps.map((s,n)=>`<div class="instruction"><b>${n+1}</b><span>${s}</span></div>`).join("")}</div><div class="tip-grid"><div class="tip danger"><strong>⚠ Common Mistakes</strong><span>${g.mistakes}</span></div><div class="tip good"><strong>🌱 Beginner Option</strong><span>${g.easy}</span></div></div><div class="task muscles"><div class="check">🎯</div><div><strong>Muscles Worked</strong><small>${g.muscles}</small></div></div></section><button class="primary-button" id="complete-exercise">✓ Exercise Complete</button><button class="secondary-button" id="back-session-2">Back to workout</button></main>${nav("workouts")}`;bindNav();$("back-session").onclick=overview;$("back-session-2").onclick=overview;$("complete-exercise").onclick=()=>showRest(index);}
 function showRest(doneIndex){stopTimer();const next=exercises[doneIndex+1],rest=Math.max(1,Number(exercises[doneIndex]?.rest_seconds||45));let left=rest;const g=next?guideFor(next):null;app.innerHTML=`<header><button class="secondary-button" style="width:auto;margin:0;padding:9px 13px" id="rest-back">‹</button><strong>Rest Time</strong><span>Next</span></header><main><section class="rest-screen"><div class="rest-ring" id="rest-ring" style="--rest-progress:100%"><div class="rest-ring-content"><strong id="rest-value">${String(left).padStart(2,"0")}</strong><small>Resting…</small></div></div><h2>Catch your breath</h2><p style="color:var(--muted)">Get ready for the next exercise.</p>${next?`<div class="next-card"><img src="${g.image}" alt="${next.name}"><div><strong>Next Exercise</strong><small>${next.name}</small><small>${text(next)}</small></div></div>`:`<div class="next-card"><div class="check">✓</div><div><strong>Final exercise complete</strong><small>You're almost done!</small></div></div>`}<button class="primary-button" id="skip-rest">${next?"Skip Rest & Start Next":"Finish Workout"}</button></section></main>${nav("workouts")}`;bindNav();$("rest-back").onclick=()=>showExercise(doneIndex);const update=()=>{const pct=Math.round(left/rest*100);$("rest-value").textContent=String(left).padStart(2,"0");$("rest-ring").style.setProperty("--rest-progress",pct+"%");if(left<=0){stopTimer();next?showExercise(doneIndex+1):finishWorkout();return}left--};$("skip-rest").onclick=()=>{stopTimer();next?showExercise(doneIndex+1):finishWorkout()};update();timer=setInterval(update,1000)}
 async function finishWorkout(){stopTimer();const duration=Math.max(1,Number(w.duration_minutes||Math.ceil(exercises.reduce((a,e)=>a+Number(e.duration_seconds||0),0)/60)));const r=await supabase.from("workout_logs").insert({user_id:user.id,workout_id:id,completed_at:new Date().toISOString(),duration_minutes:duration,calories_burned:Math.round(duration*7)});app.innerHTML=`<main><section class="hero complete-card"><div class="complete-icon">✓</div><span>WORKOUT COMPLETE</span><h2>Great job! 🎉</h2><p>You finished ${w.name}. That's another step forward.</p><div class="stats"><div>⏱️<strong>${duration} min</strong><small>Duration</small></div><div>🔥<strong>${Math.round(duration*7)}</strong><small>Calories</small></div><div>✓<strong>${exercises.length}/${exercises.length}</strong><small>Exercises</small></div></div>${r.error?`<p class="message error">Workout wasn't saved: ${r.error.message}</p>`:'<p class="message">Workout saved successfully ✓</p>'}<button class="primary-button" id="done-back">Back to Workouts</button></section></main>${nav("workouts")}`;bindNav();$("done-back").onclick=renderLibrary}
 overview();
 }
})();