(()=>{
 const originalRender=window.render;
 const guides={
  "bodyweight squat":{image:"assets/exercises/bodyweight-squat.svg",how:"Stand with feet about shoulder-width apart. Push your hips back like sitting into a chair, bend your knees, then push through your feet to stand.",mistakes:"Do not let your knees collapse inward or rush the movement.",easy:"Use a chair behind you as a target and squat only as low as comfortable.",muscles:"Thighs, glutes and core."},
  "incline push-up":{image:"assets/exercises/incline-pushup.svg",how:"Place your hands on a sturdy raised surface. Keep your body straight, bend your elbows to lower your chest, then push away.",mistakes:"Do not let your hips sag or flare your elbows too far out.",easy:"Use a wall or higher surface if a bench feels difficult.",muscles:"Chest, shoulders, arms and core."},
  "glute bridge":{image:"assets/exercises/glute-bridge.svg",how:"Lie on your back with knees bent and feet flat. Squeeze your glutes and lift your hips, then lower slowly.",mistakes:"Do not over-arch your lower back. Lift from your hips and squeeze at the top.",easy:"Lift your hips only part way if the full movement is uncomfortable.",muscles:"Glutes, hamstrings and core."},
  "plank":{image:"assets/exercises/plank.svg",how:"Place your forearms under your shoulders. Extend your legs, brace your stomach and keep your body in one straight line while breathing normally.",mistakes:"Do not let your hips sag or rise too high. Keep your neck relaxed.",easy:"Drop your knees to the floor while keeping your body straight from knees to head.",muscles:"Core, shoulders and hips."},
  "dead bug":{image:"assets/exercises/dead-bug.svg",how:"Lie on your back with arms up and knees bent. Slowly extend one arm and the opposite leg, return, then switch sides.",mistakes:"Keep your lower back gently against the floor and move slowly.",easy:"Move only your arms first, then add the legs.",muscles:"Deep core and hip muscles."},
  "bird dog":{image:"assets/exercises/bird-dog.svg",how:"Start on hands and knees. Reach one arm forward and the opposite leg back. Pause, return, and switch sides.",mistakes:"Keep your hips level instead of twisting your body.",easy:"Lift only one arm or one leg at a time.",muscles:"Core, back, shoulders and glutes."},
  "side plank":{image:"assets/exercises/side-plank.svg",how:"Lie on your side with your forearm under your shoulder. Lift your hips and keep your body in a straight line.",mistakes:"Do not let your hips drop or rotate your shoulders forward.",easy:"Keep your bottom knee on the floor for support.",muscles:"Core, shoulders and hips."},
  "reverse lunges":{image:"assets/exercises/reverse-lunge.svg",how:"Stand tall, step one foot backward, bend both knees comfortably, then push through the front foot to return.",mistakes:"Keep the front knee tracking over the foot and avoid rushing.",easy:"Hold a wall or chair for balance and take a smaller step.",muscles:"Glutes, thighs and calves."},
  "calf raises":{image:"assets/exercises/calf-raises.svg",how:"Stand tall with feet hip-width apart. Slowly rise onto the balls of your feet, pause, then lower your heels with control.",mistakes:"Do not bounce or roll your ankles outward.",easy:"Hold a wall or chair for balance.",muscles:"Calves and ankles."},
  "march in place":{image:"assets/exercises/march-in-place.svg",how:"Stand tall and alternate lifting your knees while gently swinging your arms. Keep a steady comfortable rhythm.",mistakes:"Keep your chest tall and land softly.",easy:"Lift the knees lower and slow the pace.",muscles:"Legs, hips and cardiovascular system."},
  "jumping jacks":{image:"assets/exercises/jumping-jacks.svg",how:"Start with feet together. Jump your feet apart while raising your arms, then return to the starting position.",mistakes:"Land softly and keep your knees slightly bent.",easy:"Step one foot out at a time instead of jumping.",muscles:"Legs, shoulders and cardiovascular system."},
  "high knees":{image:"assets/exercises/high-knees.svg",how:"Run or march in place while driving your knees upward one at a time. Pump your arms naturally.",mistakes:"Stay tall and land softly instead of stomping.",easy:"March slowly and lift the knees only as high as comfortable.",muscles:"Legs, hips and cardiovascular system."}
 };
 const guideFor=e=>guides[String(e.name||"").trim().toLowerCase()];
 window.render=function(page){if(page!=="workouts")return originalRender(page);app.innerHTML=`<header><div><small>WORKOUTS</small><h1>Let's get moving 💪</h1></div><div class="avatar">${(profile.name||"M")[0].toUpperCase()}</div></header><main><section class="hero"><span>MIKEFIT LIBRARY</span><h2>Choose your workout</h2><p>Pick a session that fits your time, level and goal.</p></section><section><div id="workout-list"><p>Loading workouts…</p></div></section></main>${nav("workouts")}`;supabase.from("workouts").select("*").order("id").then(({data,error})=>{const box=$("workout-list");if(error){box.innerHTML=`<div class="task"><div><strong>Couldn't load workouts</strong><small>${error.message}</small></div></div>`;return}if(!data?.length){box.innerHTML='<div class="task"><div><strong>No workouts available yet.</strong></div></div>';return}box.innerHTML=data.map(w=>`<button class="task task-button workout-card" data-workout="${w.id}"><div class="check">${w.icon||"🏋️"}</div><div><strong>${w.name}</strong><small>${w.duration_minutes||0} min • ${w.level||"All levels"} • ${w.category||"Workout"}</small><small>${w.description||"Ready when you are."}</small></div><span>›</span></button>`).join("");box.querySelectorAll("[data-workout]").forEach(b=>b.onclick=()=>openWorkout(Number(b.dataset.workout)))});app.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>render(b.dataset.page));};
 async function openWorkout(id){const [{data:w,error:we},{data:ex,error:ee}]=await Promise.all([supabase.from("workouts").select("*").eq("id",id).single(),supabase.from("workout_exercises").select("*").eq("workout_id",id).order("sort_order")]);if(we||ee){toastMsg((we||ee).message);return}let started=false,seconds=0,timer=null;const exercises=ex||[];const exerciseText=e=>e.duration_seconds?`${e.duration_seconds}s`:e.sets&&e.reps?`${e.sets} × ${e.reps}`:`${e.sets||""} sets`;
 app.innerHTML=`<header><div><small>${w.category||"WORKOUT"}</small><h1>${w.name}</h1></div><div class="avatar">${w.icon||"🏋️"}</div></header><main><section class="hero"><span>${w.level||"ALL LEVELS"}</span><h2>${w.duration_minutes||0} minutes</h2><p>${w.description||"Complete each exercise at your own pace."}</p></section><section><div class="section-title"><h2>Exercises</h2><span>${exercises.length} moves</span></div><div id="exercise-list">${exercises.map((e,i)=>{const d=guideFor(e);return `<article class="exercise-card"><div class="task"><div class="check">${i+1}</div><div><strong>${e.name}</strong><small>${exerciseText(e)}${e.rest_seconds?` • ${e.rest_seconds}s rest`:""}</small></div></div>${d?`<img class="exercise-illustration" src="${d.image}" alt="${e.name} exercise pictorial guide"><div class="exercise-guide"><p><strong>How to do it:</strong> ${d.how}</p><p><strong>Avoid:</strong> ${d.mistakes}</p><p><strong>Beginner option:</strong> ${d.easy}</p><p><strong>Works:</strong> ${d.muscles}</p></div>`:`<div class="exercise-guide"><p><strong>How to do it:</strong> Move slowly and keep your body controlled throughout each rep.</p></div>`}</article>`}).join("")||'<div class="task"><div><strong>No exercises added yet.</strong></div></div>'}</div><div id="workout-timer" class="hero" style="display:none"><span>WORKOUT TIME</span><h2 id="timer-value">00:00</h2><p>Keep going — you’ve got this.</p></div><button class="primary-button" id="start-workout">Start workout</button><button class="secondary-button" id="back-workouts">Back to workouts</button></section></main>${nav("workouts")}`;
 $("back-workouts").onclick=()=>render("workouts");app.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>render(b.dataset.page));
 $("start-workout").onclick=async()=>{if(started){clearInterval(timer);started=false;$("start-workout").textContent="Resume workout";toastMsg("Workout paused");return}if(seconds>0&&$("start-workout").textContent==="Resume workout"){started=true;$("start-workout").textContent="Pause workout"}else{started=true;$("start-workout").textContent="Pause workout";$("workout-timer").style.display="block"}timer=setInterval(()=>{seconds++;$("timer-value").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`},1000);toastMsg("Workout started 💪");$("start-workout").onclick=async()=>{clearInterval(timer);const duration=Math.max(1,Math.ceil(seconds/60));const r=await supabase.from("workout_logs").insert({user_id:user.id,workout_id:id,completed_at:new Date().toISOString(),duration_minutes:duration,calories_burned:Math.round(duration*7)});if(r.error)toastMsg(r.error.message);else{toastMsg("Workout completed 🎉");render("workouts")}}};
 }
})();